/*************************************************
Initially Generated by SSoT.me - 2019
    EJ Alexandra - An airtable Tool
    This file WILL NOT be overwritten once changes are made.
*************************************************/
using AirtableDirect.CLI.Lib.DataClasses;

namespace AirtableToDotNet.APIWrapper
{
    /// <summary>
    /// Airtable API Wrapper for the AirtableDirectCLI Base
    /// </summary>
    public partial class AirtableDirectCLIAirtableAPIWrapper
    {
        public AirtableDirectCLIAirtableAPIWrapper(string apiKey, string baseId, string baseUrlFormatString = "https://api.airtable.com/v0/{0}/") : base(apiKey, baseId, baseUrlFormatString)
        {
        }
    }
}
                  